python run_benchmark_separate.py  --config-name=benchmark_libero_separate \
            --multirun agents=goal_ddpm_mamba_encdec_separate \
            agent_name=ddpm_mamba_cross \
            folder_name=separate_with_hand_1000_epoch_ckpts \
            epoch=1000 \
            is_bl3_all=False \
            task_order_index=0 \
            task_suite=libero_90 \
            group=libero_90_ddpm_mamba_cross_goal \
            obs_seq=5 \
            train_batch_size=128 \
            n_layer_encoder=8 \
            mamba_encoder_cfg.d_state=8 \
            mamba_decoder_cfg.d_state=8 \
            enc_conv=2 \
            dec_conv=2 \
            seed=10000 \
            wandb.entity=yygx \
            wandb.project=mail
